SELECT ted.grid_id,
       ted.tree_count,
       ted.mean_tree_age,
       ted.std_tree_age,
       ted.min_age,
       ted.max_age,
       ted.percentile_25,
       ted.percentile_75,
       cs.count_acer,
       cs.count_alnus,
       cs.count_betula,
       cs.count_carpinus,
       cs.count_crataegus,
       cs.count_fraxinus,
       cs.count_malus,
       cs.count_onbekend,
       cs.count_overig,
       cs.count_platanus,
       cs.count_populus,
       cs.count_prunus,
       cs.count_quercus,
       cs.count_robinia,
       cs.count_salix,
       cs.count_tilia,
       cs.count_ulmus,
       ctd.count_01_02,
       ctd.count_02_03,
       ctd.count_03_05,
       ctd.count_05_1,
       ctd.count_1_15,
       ctd.count_over_15,
       ctd.count_unknown                                       AS count_unknown_diameter,
       cth.count_up_to_6,
       cth.count_6_to_9,
       cth.count_9_to_12,
       cth.count_12_to_15,
       cth.count_15_to_18,
       cth.count_18_to_24,
       cth.count_over_24,
       cth.count_unknown                                       AS count_unknown_height,
       COALESCE(spv.sum_area_1, 0::double precision)           AS sum_area_1,
       COALESCE(spv.sum_area_2, 0::double precision)           AS sum_area_2,
       COALESCE(spv.sum_area_3, 0::double precision)           AS sum_area_3,
       COALESCE(spv.sum_area_4, 0::double precision)           AS sum_area_4,
       COALESCE(spv.sum_area_5, 0::double precision)           AS sum_area_5,
       COALESCE(spv.sum_area_6, 0::double precision)           AS sum_area_6,
       COALESCE(spv.sum_area_7, 0::double precision)           AS sum_area_7,
       COALESCE(spv.sum_area_20, 0::double precision)          AS sum_area_20,
       COALESCE(spv.sum_area_remediation, 0::double precision) AS sum_area_remediation,
       COALESCE(spv.sum_area_unknown, 0::double precision)     AS sum_area_unknown,
       COALESCE(upv.drainable, 0::double precision)            AS drainable,
       COALESCE(upv.not_drainable, 0::double precision)        AS not_drainable,
       COALESCE(upv.total_underwater, 0::double precision)     AS total_underwater
FROM tree_age_description ted
         JOIN count_species cs ON ted.grid_id::text = cs.grid_id::text
         JOIN count_tree_diameter ctd ON ted.grid_id::text = ctd.grid_id::text
         JOIN count_tree_height cth ON ted.grid_id::text = cth.grid_id::text
         LEFT JOIN soil_pct_view spv ON ted.grid_id::text = spv.grid_id::text
         LEFT JOIN underwater_pct_view upv ON ted.grid_id::text = upv.grid_id::text;